# Generated by Django 4.0.2 on 2022-02-08 23:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import core.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PetOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="Full Name"),
                ),
                ("address", models.CharField(max_length=1000, verbose_name="Address")),
                (
                    "phone",
                    models.CharField(
                        help_text="Phone number format: +901234567890.",
                        max_length=20,
                        validators=[core.utils.PhoneNumberValidator()],
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="E-mail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pet Owner",
                "verbose_name_plural": "Pet Owners",
            },
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                ("type", models.CharField(max_length=50, verbose_name="Type")),
                ("genus", models.CharField(max_length=50, verbose_name="Genus")),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                ("age", models.PositiveSmallIntegerField(verbose_name="Age")),
                (
                    "description",
                    models.TextField(max_length=2000, verbose_name="Description"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pets.petowner",
                        verbose_name="Pet Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "pet",
                "verbose_name_plural": "pets",
            },
        ),
    ]
